// Generated by https://quicktype.io

export interface MapBoxSearch {
    suggestions: Suggestion[];
    attribution: string;
}

export interface Suggestion {
    name:              string;
    mapbox_id:         string;
    feature_type:      string;
    place_formatted:   string;
    context:           Context;
    language:          string;
    maki?:             string;
    metadata?:         ExternalIDS;
    poi_category?:     string[];
    poi_category_ids?: string[];
    external_ids?:     ExternalIDS;
    brand?:            string[];
}

export interface Context {
    country?:  Country;
    region?:   Region;
    district?: District;
}

export interface Country {
    id:                   string;
    name:                 string;
    country_code:         string;
    country_code_alpha_3: string;
}

export interface District {
    id:   string;
    name: string;
}

export interface Region {
    id:               string;
    name:             string;
    region_code:      string;
    region_code_full: string;
}

export interface ExternalIDS {
}
